# Generated by Django 2.2 on 2019-05-19 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stechec', '0004_tournament_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='file_options',
        ),
        migrations.RemoveField(
            model_name='match',
            name='options',
        ),
        migrations.AddField(
            model_name='map',
            name='contents',
            field=models.TextField(default='', verbose_name='contenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='map',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='matches',
                to='stechec.Map',
                verbose_name='carte',
            ),
        ),
    ]
