# Generated by Django 2.2.10 on 2020-03-07 10:29

from django.db import migrations, models
import prologin.concours.stechec.models


class Migration(migrations.Migration):

    dependencies = [
        ('stechec', '0008_add_status_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='priority',
            field=models.IntegerField(
                default=prologin.concours.stechec.models.MatchPriority(500),
                help_text='Match scheduling priority, higher is faster.',
                verbose_name='priority',
            ),
        ),
    ]
