# Generated by Django 2.2.10 on 2020-03-14 15:47

from django.db import migrations, models
import prologin.concours.stechec.models


class Migration(migrations.Migration):

    dependencies = [
        ('stechec', '0009_match_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(
                choices=[
                    ('creating', 'En cours de création'),
                    ('new', 'En attente de lancement'),
                    ('pending', 'En cours de calcul'),
                    ('done', 'Terminé'),
                    ('failed', 'Échec'),
                    ('cancelled', 'Annulé'),
                ],
                default='creating',
                max_length=100,
                verbose_name='statut',
            ),
        ),
    ]
