# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django_prometheus.models


def initial_data(apps, schema_editor):
    UIDPool = apps.get_model('udb', 'UIDPool')
    UIDPool(last=0, group="user", base=1000, pk=1).save()
    UIDPool(last=0, group="orga", base=2000, pk=2).save()
    UIDPool(last=0, group="root", base=3000, pk=3).save()


class Migration(migrations.Migration):

    dependencies = [
        ('udb', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIDPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('user', 'Contestant'), ('orga', 'Organizer'), ('root', 'root')], max_length=20, unique=True, verbose_name='For type')),
                ('base', models.IntegerField(unique=True, verbose_name='Base UID')),
                ('last', models.IntegerField(blank=True, default=0, verbose_name='Last allocation')),
            ],
            options={
                'verbose_name': 'UID Pool',
                'verbose_name_plural': 'UID Pools',
                'ordering': ('group',),
            },
        ),
        migrations.RunPython(initial_data),
    ]
