# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udb', '0003_uidpool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(db_index=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(regex='^([a-z_][a-z0-9_]{0,30})$')]),
        ),
    ]
