# Generated by Django 2.2.13 on 2020-08-28 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTheia',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('host', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
            ],
            options={'unique_together': {('host', 'room', 'port')},},
        ),
        migrations.CreateModel(
            name='UserMachine',
            fields=[
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'workspace',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='webide.MachineTheia',
                    ),
                ),
            ],
        ),
    ]
