{
 "title": "nfsd",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "node_nfsd_server_rpcs_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_server_rpcs_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_packets_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_packets_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_connections_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_connections_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_disk_bytes_read_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_disk_bytes_read_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_rpc_errors_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_rpc_errors_total[5m])",
     "legendFormat": "{{instance}} ({{error}})"
    }
   ]
  },
  {
   "title": "node_nfsd_read_ahead_cache_not_found_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_read_ahead_cache_not_found_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_file_handles_stale_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_file_handles_stale_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_requests_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_requests_total[5m])"
    }
   ]
  },
  {
   "title": "node_nfsd_reply_cache_nocache_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_reply_cache_nocache_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_reply_cache_misses_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_reply_cache_misses_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_reply_cache_hits_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nfsd_reply_cache_hits_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "node_nfsd_read_ahead_cache_size_blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_nfsd_read_ahead_cache_size_blocks[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}