{
 "title": "Journal aggregator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uploaded entries",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_journal_upload_entries_count_sum"
    }
   ]
  },
  {
   "title": "Entries per batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_journal_upload_entries_count_sum[5m])/rate(journal_send_rounds_total[5m])"
    }
   ]
  },
  {
   "title": "Entries per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_journal_upload_entries_count_sum[5m])"
    }
   ]
  },
  {
   "title": "Simultaneous uploads to ES",
   "type": "graph",
   "description": "Should be super close to 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concurrent_uploads" }
   ]
  },
  {
   "title": "Journal upload exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(journal_send_exceptions_total[5m])"
    }
   ]
  }
 ]
}