# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stechec', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='graphic_lang',
            field=models.ImageField(null=True, upload_to='graph/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='graphic_loc',
            field=models.ImageField(null=True, upload_to='graph/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
