# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stechec', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
