# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stechec', '0003_add_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='graphic_repartition',
            field=models.ImageField(null=True, upload_to='graph/'),
        ),
    ]
