# Generated by Django 2.2 on 2019-06-01 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stechec', '0005_maps_in_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayerCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='commentaire')),
                ('include_jury_report', models.BooleanField(default=False, verbose_name='inclure dans le rapport de jury')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='stechec.TournamentPlayer', verbose_name='joueur')),
            ],
            options={
                'verbose_name': 'correction du joueur',
                'verbose_name_plural': 'corrections des joueurs',
            },
        ),
    ]
