# Generated by Django 2.2.10 on 2020-03-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stechec', '0008_add_match_status_discarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='priority',
            field=models.IntegerField(
                default=100,
                help_text='Match scheduling priority, higher is faster.',
                verbose_name='prioriy',
            ),
        ),
    ]
