#!/bin/sh

run_latehook() {
    find /new_root/var/log -type d > /var_log_list
    mount -t tmpfs tmpfs /new_root/var/log
    mount -t tmpfs tmpfs /new_root/var/tmp
    mount -t tmpfs tmpfs /new_root/var/spool/mail
    mount -t tmpfs tmpfs /new_root/var/lib/kdm
    mount -t tmpfs tmpfs /new_root/home
    while read d; do
        mkdir -p "$d"
    done < /var_log_list
}

# vim: set ft=sh ts=4 sw=4 et:
