{
 "title": "Concours",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "masternode_workers" }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Matches - New",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "concours_match_status_count{status=\"new\"}"
    }
   ]
  },
  {
   "title": "Matches - Creating",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "concours_match_status_count{status=\"creating\"}"
    }
   ]
  },
  {
   "title": "Matches - Pending",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "concours_match_status_count{status=\"pending\"}"
    }
   ]
  },
  {
   "title": "Matches - Done (rate per second)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(concours_match_status_count{status=\"done\"}[1m])"
    }
   ]
  },
  {
   "title": "Champions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(concours_champion_status_count) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}