{
 "title": "System",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "ram available (users)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"pas.*|alt.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ram available (services)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"(gw|web|monitoring|rhfs).*\",job=\"node-services\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processes running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_running" }
   ]
  },
  {
   "title": "Process blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg_over_time(node_procs_blocked[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{instance=~\"(pas|alt).*:9100\",mode=\"user\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{instance=~\"(pas|alt).*:9100\",mode=\"system\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU IO Wait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"(pas|alt).*:9100\",mode=\"iowait\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU load over 5 minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"(pas|alt).*:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU IRQ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"(pas|alt).*:9100\",mode=\"irq\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Soft IRQ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"(pas|alt).*:9100\",mode=\"softirq\"}[5m])) by (mode)"
    }
   ]
  },
  {
   "title": "Average processes running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{instance=~\"(pas|alt).*:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Steal",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"(pas|alt).*:9100\",mode=\"steal\"}[5m])) by (mode)"
    }
   ]
  }
 ]
}