{
 "title": "RHFS *",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "IO Wait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"rhfs.*:9100\",mode=\"iowait\"}[5m]))by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"(rhfs).*:9100\",mode=\"system\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"(rhfs).*:9100\",job=\"node-services\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sent Packets Avg over 10m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_packets_total{instance=~\"rhfs(.*):9100\"}[10m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"rhfs(.*):9100\",device!=\"lo\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"rhfs(.*):9100\",mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incoming Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{instance=~\"rhfs(.*):9100\",device!=\"lo\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg of bytes transfered over 10m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"rhfs(.*):9100\"}[10m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO wait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"(rhfs).*:9100\",mode=\"iowait\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Avg number of bytes over 10min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"rhfs(.*):9100\"}[10m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HFS, User",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(hfs_running_nbd_gauge) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of received packets AVG over 10Min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{instance=~\"rhfs(.*):9100\"}[10m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}