{
 "title": "Radio",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Actions /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(action{job=\"radio\", name!=\"QUEUE/REQUEST\", name!=\"SONGUPDATE/SUBSCRIBE\", name!=\"SONGUPDATE/UNSUBSCRIBE\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Systemd services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"misc:9100\",name=~\"spotify.service|.*djraio.*\", state=\"active\"} == 1"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Volume" }
   ],
   "targets": [
    {
     "expr": "mpv_volume{job=\"radio\"}"
    }
   ]
  },
  {
   "title": "Database query performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(database_query_timing{job=\"radio\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Websockets message traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_websockets[5m])) by (name)"
    }
   ]
  }
 ]
}