{
 "title": "masternode",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "masternode_workers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "masternode_workers" }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "masternode_workers" }
   ]
  },
  {
   "title": "masternode_tasks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "masternode_tasks" }
   ]
  },
  {
   "title": "Champions status rate:5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(concours_champion_status_count[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Matches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(concours_match_status_count{status!=\"done\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Targets up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{instance=~\"pas.*\",job=\"node-users\"})",
     "legendFormat": "pas"
    },
    {
     "expr": "sum(up{instance=~\"alt.*\",job=\"node-users\"})",
     "legendFormat": "alt"
    }
   ]
  },
  {
   "title": "masternode_worker_timeout by 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(masternode_worker_timeout[5m])"
    }
   ]
  },
  {
   "title": "delta masternode_request_compilation_task over 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(masternode_request_compilation_task_created[5m])"
    }
   ]
  },
  {
   "title": "CPU load (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "masternode_bad_result",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "masternode_bad_result_total" }
   ]
  },
  {
   "title": "masternode_task_redispatch over 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(masternode_task_redispatch_total[5m])"
    }
   ]
  }
 ]
}